seq = "CCGGACCATAGTTTTCCCACTCTTCCCGTGTCCACTGATCGTGGACGTTAGCGATACAACTCTCAATAATATTGTACCATAGTAACCCGTTTAGAAGGTAACGCCTGACATGCAGACTGTGTGTATACGTCCCTCTAGCGCGTCGGTTATAGAAAGGGTTTCTTAAGCGTGGCTCACACCAGACGCACAGATGTGTTCGACATCGTGAACCCCGTCAACCTGTCGGAAGACCATTCAGGCCCAAAAAGTAAGATGATTACAACAAGCAAATTTTCTCCTATCGTCCGTAATCCAGATTAATGCGTGTACTCCGTGGAGTTGTGCGAGCATAGAGATGAGACGTACCCTTGAATATAGAAATCCCCGCCCATAAAATTAATGGCGGGTAGTACGCTGCTGCCCCCCGTCTCATCATTTAGGCCTGTTAGGTATGAAGGCACCGTTGTTGTAACGATACCCCGGACGACGACACTCACACCCCCATCCCCGCCACTTATATAGGAACCAGAGGTTATCCTTCGCAATATTCCCGGGATGGCTATCCACCCCCTAGAAGCGTATCAGTCTTCTCTGCGCGCGAGAGCGGTCTGCTGACACTAAGGACGGCGACCCAGCTCGGTCAACCGCGGTTAGGTATTTCGACGCCCCACCATACTTTAGCCAACCTCTTCCATGCGCTGCGTCAATTTCATGCAATGTACCGTCCCGCCGTTAAGAGAGTCTCTATACAAACAACTCGCAGACAGATCTTGAAGACATAGGCCAGAGAAAGCAAGTTAGAAACCGGACTGCTGACCCTTCCCCTCTGAGGACGCGATTGACGTTCGGGGCAAACGAGGTCGGGCGAAAAAGCCCGATGTCTCTCCCACGGCATTACATCCAAGCCCTGTAGGCTCTTATCCCAAGTCGACCTCGAAAGCTATGT";
seqList = [];
revSeqList = [];
revSeq = "";

seqList = list(seq);
seqList.reverse();
revSeq = ''.join(seqList);

revSeq = revSeq.replace("A", "t");
revSeq = revSeq.replace("T", "a");
revSeq = revSeq.replace("G", "c");
revSeq = revSeq.replace("C", "g");

revSeq = revSeq.replace("a", "A");
revSeq = revSeq.replace("t", "T");
revSeq = revSeq.replace("g", "G");
revSeq = revSeq.replace("c", "C");

print revSeq;